规范化所有命令行的帮助文档

diff --git a/bin/build-image b/bin/build-image
--- a/bin/build-image
+++ b/bin/build-image
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 [[ -L $0 ]] && SCRIPT_FILE=`readlink -fn $0` || SCRIPT_FILE=$0
 pushd `dirname "${SCRIPT_FILE}"` >/dev/null
@@ -33,7 +33,7 @@ function _extra_help() {
 HELP_ARGS["c"]="optional,Clean local build image."
 HELP_ARGS["p"]="optional,Push image to registry."
 HELP_ARGS["b:build_name"]="Project name to build."
-HELP_ARGS["D"]="-"
+HELP_ARGS["D"]="optional,Dry run command for test."
 
 function _build() {
     MODULE=
@@ -132,6 +132,14 @@ if [[ ! -d "${BUILD_DIR}" ]]; then
 fi
 
 cd "${BUILD_DIR}"
+
+ORIGIN_TEMPLATE_FILE="${TEMPLATE_BASE}/dockerfile/${BUILD_NAME}/dockerfile.template"
+if [[ ! -f "${ORIGIN_TEMPLATE_FILE}" ]]; then
+    error "dockerfile template missing."
+    exit 1
+fi
+
+$SUDO cp -f "${ORIGIN_TEMPLATE_FILE}" ./
 
 ls ${PATTERN} &>/dev/null
 if [[ $? -ne 0 ]]; then
diff --git a/bin/ngeuser b/bin/ngeuser
--- a/bin/ngeuser
+++ b/bin/ngeuser
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 [[ -L $0 ]] && SCRIPT_FILE=`readlink -fn $0` || SCRIPT_FILE=$0
 pushd `dirname "${SCRIPT_FILE}"` >/dev/null
@@ -23,11 +23,21 @@ DB_USER=root
 DB_PASS=quantdo123456
 DB_NAME=digital
 
-USER_BASE_DIR="/opt/pyload/CSV"
+USER_BASE_DIR="${DATA_BASE:=/opt}/pyload/CSV"
 ORIGN_USER_FILE="${USER_BASE_DIR}/Users.csv"
 SLAVE_USER_FILE="${USER_BASE_DIR}/users.csv"
 
 PYLOAD_GROUP="pyload"
+
+HELP_ARGS["u:db_user"]="optional,User used in db connection with root privilege, if not specified, default auth will be used."
+HELP_ARGS["p:db_pass"]="optional,Password used in db connection with root privilege, if not specified, default auth will be used."
+HELP_ARGS["d:db_name"]="optional,DB name used in connection, if not specified, default \`digital\` will be used."
+HELP_ARGS["g:group_name"]="optional,Group name used when pub user CSV to all pyload members if not specified, default: \"pyload\" will be used."
+
+HELP_COMMANDS["init"]="Init 10000 pre-defined users for testing."
+HELP_COMMANDS["get"]="Retrive pre-defined users'info initiated by \`init\` command from DB."
+HELP_COMMANDS["pub"]="Publish retrived users CSV to all pyload members."
+HELP_COMMANDS["deploy"]="Combine of \`get\` & \`pub\` command."
 
 function _init_users() {
     local _RESULT
@@ -65,6 +75,31 @@ function _pub_users() {
     allscp -g${PYLOAD_GROUP} "${ORIGN_USER_FILE}"
     info "publishing finished."
 }
+
+while getopts :u:p:d:g:h FLAG; do
+    case $FLAG in
+        u)
+            DB_USER=${OPTARG}
+        ;;
+        p)
+            DB_PASS=${OPTARG}
+        ;;
+        d)
+            DB_NAME=${OPTARG}
+        ;;
+        g)
+            PYLOAD_GROUP=${OPTARG}
+        ;;
+        h)
+            _help >&2
+            exit
+        ;;
+        *)
+            error "invalid args: $*"
+        ;;
+    esac
+done
+shift $((OPTIND-1))
 
 if [[ $# -lt 1 ]]; then
     error "missing command."
