新增编译后发布功能

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -17,11 +17,28 @@ JAVA_MODULE_DEFINE["digital"]="digital-rest digital-serviceimpl"
 JAVA_MODULE_DEFINE["trade-system"]="trade-clear-database trade-clear-memory trade-match trade-order trade-query"
 JAVA_MODULE_DEFINE["service-management"]="exchange-index-server scheduler-server sms-mail-server trade-base"
 
+declare -A PUB_MAPPER
+PUB_MAPPER["digital-rest"]=digital-rest
+PUB_MAPPER["digital-serviceimpl"]=digital-serviceimpl
+PUB_MAPPER["trade-clear-database"]=trade-tmdb
+PUB_MAPPER["trade-clear-memory"]=trade-clear
+PUB_MAPPER["trade-match"]=trade-match
+PUB_MAPPER["trade-order"]=trade-order
+PUB_MAPPER["trade-query"]=trade-query
+PUB_MAPPER["exchange-index-server"]=service-index
+PUB_MAPPER["scheduler-server"]=service-scheduler
+PUB_MAPPER["sms-mail-server"]=service-sms
+PUB_MAPPER["trade-base"]=service-tradebase
+PUB_MAPPER["365MEX"]=quant-coin
+PUB_MAPPER["webadmin-front"]=quant-coinMS
+
 MAVEN_MIRROR_PORT=8181
 UPDATE_GIT=0
+PUBLISH=0
 COMMIT_ID=
 
 HELP_ARGS["u"]="optional,Pull lastest update from master@github."
+HELP_ARGS["p"]="optional,Publish new build to nginx or docker registry."
 HELP_ARGS["c:npm|mvn"]="optional,Specify compiler type for project, and ignore all others."
 
 HELP_POSITION_ARGS[0]="{all | project_name}..."
@@ -140,6 +157,28 @@ function _npm_compile() {
 
         cd build && tar -czvf "${_tar_file}" . --exclude "*.tar.gz" &>/dev/null
         ls -l --color=auto "${_tar_file}"
+
+        if [[ ${PUBLISH} -ne 1 ]]; then
+            return
+        fi
+
+        if [[ x"${PUB_MAPPER[$_project_base_name]}" == "x" ]]; then
+            error "no publish mapper for ${_project_base_name}"
+            exit 1
+        fi
+
+        local _nginx_data_base="${DATA_BASE:=/opt}/nginx/data"
+        local _project_pub_dir="${_nginx_data_base}/${PUB_MAPPER[$_project_base_name]}"
+
+        info "publishing ${_project_base_name}[${COMMIT_ID}] to ${_project_pub_dir}"
+        
+        # aleady cd build on tar build files
+        ${SUDO} tar -xzvf "${_tar_file}" -C "${_project_pub_dir}"
+        if [[ $? -ne 0 ]]; then
+            error "publishing ${_project_base_name}[${COMMIT_ID}] failed."
+            exit 1
+        fi
+        nginx-pub data ${PUB_MAPPER[$_project_base_name]}
     popd &>/dev/null
 }
 
@@ -176,7 +215,6 @@ EOF
         fi
 
         info "start to build project: ${_project_base_name}[${COMMIT_ID}]"
-
 
         if [[ -d conf ]]; then
             _env_arg="-Denv=dev"
@@ -223,13 +261,44 @@ EOF
             error "project[${_project_base_name}] build failed."
             exit 1
         fi
+
+        if [[ ${PUBLISH} -ne 1 ]]; then
+            return
+        fi
+
+        local _project_version=`sed -n '/<version>.*<\/version>/ s/'"[[:space:]]"'*<version>\(.*\)<\/version>/\1/p; ' pom.xml`
+
+        for module in ${JAVA_MODULE_DEFINE[$_project_base_name]}; do
+            if [[ x"${PUB_MAPPER[$module]}" == "x" ]]; then
+                error "no publish mapper for ${_project_base_name}[${module}]"
+                exit 1
+            fi
+
+            local _publish_name="${PUB_MAPPER[$module]}-${_project_version}.jar"
+            local _docker_hub_base="${DATA_BASE:=/opt}/docker-hub"
+            local _docker_hub_prj_name=`echo ${PUB_MAPPER[$module]} | cut -d'-' -f1`
+            local _publish_file="${_docker_hub_base}/${_docker_hub_prj_name}/${_publish_name}"
+
+            info "publishing ${_project_base_name} ${module}[${COMMIT_ID}] to ${_publish_file}"
+            
+            ${SUDO} cp -f ${module}/target/*.jar "${_publish_file}"
+            if [[ $? -ne 0 ]]; then
+                error "publishing ${_project_base_name} ${module}[${COMMIT_ID}] failed."
+            exit 1
+        fi
+        done
+
+        build-image -cp -b${_docker_hub_prj_name} all
     popd >/dev/null
 }
 
-while getopts :c:uh FLAG; do
+while getopts :c:uph FLAG; do
     case $FLAG in
         u)
             UPDATE_GIT=1
+        ;;
+        p)
+            PUBLISH=1
         ;;
         c)
             WANTED_COMPILER=${OPTARG}
